version: "3.2"

services:
  rules:

    # use the Dockerfile next to this file
    # TODO(plural): Switch to the container image.
    build:
      dockerfile: Dockerfile.deploy

    ports:
      - "8999:80"

