version: "3.2"

services:
  rules:
    restart: none
    # use the Dockerfile next to this file
    # TODO(plural): Switch to the container image.
    build:
      dockerfile: Dockerfile.deploy

    volumes:
      - rules:/var/www/html
  
  web:
    restart: unless-stopped
    image: php:8.2-cli-alpine

    ports:
      - "8999:80"
   
    volumes:
      - rules:/var/www/html

    command:
      - php
      - -S
      - 0.0.0.0:80

    working_dir: /var/www/html

volumes:
  rules:
