services:
  rules:
    restart: no
    image: registry.digitalocean.com/nsgcr/netrunner-comprehensive-rules:${RULES_IMAGE_VERSION:-latest}
    # use the Dockerfile next to this file
    build:
      dockerfile: Dockerfile.deploy

    volumes:
      - rules:/var/www/html

  web:
    restart: unless-stopped
    image: php:8.2-cli-alpine

    ports:
      - "8999:80"

    volumes:
      - rules:/var/www/html

    command:
      - php
      - -S
      - 0.0.0.0:80

    working_dir: /var/www/html

volumes:
  rules:
